name: M3U8 Simple Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yt-dlp
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Load cookie
        run: echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Create deploy folder
        run: mkdir deploy

      - name: Get stream + create file (SAFE MODE)
        run: |
          echo "Getting stream..."

          LINK=$(yt-dlp \
            --cookies cookies.txt \
            --no-warnings \
            -f "best" \
            -g "https://www.youtube.com/watch?v=EqoCJ8BPxtE" || true)

          echo "LINK=$LINK"

          if [ -z "$LINK" ]; then
            echo "FALLBACK STREAM" > deploy/stream.m3u8
          else
            echo "#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=800000
$LINK" > deploy/stream.m3u8
          fi

      - name: Deploy to Netlify
        run: |
          netlify deploy \
            --prod \
            --dir=deploy \
            --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --site=${{ secrets.NETLIFY_SITE_ID }}

      - name: Done
        run: echo "DONE"
