name: M3U8 Cookie Fix

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Repo çek
        uses: actions/checkout@v4

      - name: yt-dlp kur
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Cookie dosyası oluştur
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Link al (COOKIE ile)
        run: |
          LINK=$(yt-dlp --cookies cookies.txt --js-runtimes node -g "https://www.youtube.com/watch?v=EqoCJ8BPxtE" | head -n 1)

          echo "LINK=$LINK"

          if [ -z "$LINK" ]; then
            echo "Link alınamadı!"
            exit 1
          fi

          echo "LINK=$LINK" >> $GITHUB_ENV

      - name: M3U8 oluştur
        run: |
          printf "#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=800000\n%s\n" "$LINK" > LinkBu.m3u8

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add LinkBu.m3u8
          git commit -m "cookie fix update" || echo "no change"
          git push
